name: Lambda Function Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_lambda_function:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Test Lambda Function
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
      run: |
        RESULT=$(curl -X POST "$ENDPOINT_URL" \
          -H "Content-Type: application/json" \
          -d '{
            "body": "{\"UserID\": \"user000\", \"PsychologistID\": \"psy5678\", \"Date\": \"2023-04-27\", \"Time\": \"14:00\", \"Location\": \"123 Main St, YourCity, YS\", \"Status\": \"complete\", \"ReminderSetting\": true, \"SpecialNotes\": \"Please bring all relevant medical documents.\", \"PatientName\": \"John Doe\", \"PsychologistName\": \"Dr. Jane Smith\", \"PatientAge\": 30, \"PatientGender\": \"Male\"}"
          }')
        echo $RESULT
        if [[ $RESULT == *"Appointment created successfully"* ]]; then
          echo "Test passed"
          exit 0
        else
          echo "Test failed"
          exit 1
        fi

